# Generated by Django 6.0.6 on 2026-06-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_postulacionlaboral'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInscripcion',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_alumno', models.CharField(max_length=100)),
                ('dni_alumno', models.CharField(max_length=8)),
                ('fecha_nacimiento', models.DateField()),
                ('nivel', models.CharField(max_length=30)),
                ('turno', models.CharField(max_length=30)),
                ('nombre_tutor', models.CharField(max_length=100)),
                ('dni_tutor', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField()),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
            ],
            options={
                'db_table': 'solicitud_inscripcion',
                'managed': False,
            },
        ),
    ]
